<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;


class TestDataSeeder extends Seeder
{
    public function run()
    {
        // 外部キー制約を一時的に無効化
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // 外部キーの依存順にdelete（truncateは使わない）
        if (Schema::hasTable('business_likes')) {
            DB::table('business_likes')->delete();
        }

        DB::table('businesses')->delete();
        DB::table('quests')->delete();
        DB::table('spots')->delete();
        DB::table('users')->delete();

        // 外部キー制約を元に戻す
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // users
        DB::table('users')->insert([
            [
                'id' => 1, 'name' => 'Alice', 'email' => 'alice@example.com',
                'avatar' => '/images/profile/alice.jpg', 'header' => '/images/profile/1.jpg', 'password' => Hash::make('password'),
                'role_id' => 1, 'introduction' => 'I love traveling.', 'website_url' => 'https://alice.com',
                'zip' => '100-0001', 'address' => 'Tokyo, Japan', 'phonenumber' => '090-1111-1111',
                'instagram' => '@alice', 'facebook' => 'alice.fb', 'x' => '@alice_x', 'tiktok' => '@alice_tok',
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 2, 'name' => 'Bob', 'email' => 'bob@example.com',
                'avatar' => '/images/profile/bob.jpg', 'header' => '/images/profile/2.jpg', 'password' => Hash::make('password'),
                'role_id' => 1, 'introduction' => 'Food lover.', 'website_url' => null,
                'zip' => '150-0001', 'address' => 'Osaka, Japan', 'phonenumber' => '090-2222-2222',
                'instagram' => null, 'facebook' => null, 'x' => null, 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 3, 'name' => 'Charlie', 'email' => 'charlie@example.com',
                'avatar' => '/images/profile/charlie.jpg', 'header' => '/images/profile/3.jpg', 'password' => Hash::make('password'),
                'role_id' => 1, 'introduction' => null, 'website_url' => null,
                'zip' => '530-0001', 'address' => 'Kyoto, Japan', 'phonenumber' => '090-3333-3333',
                'instagram' => '@charlie_insta', 'facebook' => null, 'x' => '@charlie_x', 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 4, 'name' => 'David', 'email' => 'david@example.com',
                'avatar' => '/images/profile/david.jpg', 'header' => '/images/profile/4.jpg', 'password' => Hash::make('password'),
                'role_id' => 1, 'introduction' => 'Explorer.', 'website_url' => 'https://david.net',
                'zip' => '160-0001', 'address' => 'Nagoya, Japan', 'phonenumber' => '090-4444-4444',
                'instagram' => null, 'facebook' => 'david.fb', 'x' => null, 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 5, 'name' => 'Eve', 'email' => 'eve@example.com',
                'avatar' => '/images/profile/eve.jpg', 'header' => '/images/profile/5.jpg', 'password' => Hash::make('password'),
                'role_id' => 1, 'introduction' => 'Nature photographer.', 'website_url' => 'https://eve.jp',
                'zip' => '460-0001', 'address' => 'Fukuoka, Japan', 'phonenumber' => '090-5555-5555',
                'instagram' => '@eve_photo', 'facebook' => null, 'x' => null, 'tiktok' => '@eve_tok',
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 6, 'name' => 'Frank', 'email' => 'frank@example.com',
                'avatar' => '/images/profile/frank.jpg', 'header' => '/images/profile/6.jpg', 'password' => Hash::make('password'),
                'role_id' => 1, 'introduction' => null, 'website_url' => null,
                'zip' => '220-0001', 'address' => 'Sapporo, Japan', 'phonenumber' => '090-6666-6666',
                'instagram' => null, 'facebook' => null, 'x' => '@frankx', 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
        
            // role_id = 2 (business)
            [
                'id' => 7, 'name' => 'Grace', 'email' => 'grace@example.com',
                'avatar' => '/images/profile/grace.jpg', 'header' => '/images/profile/7.jpg', 'password' => Hash::make('password'),
                'role_id' => 2, 'introduction' => 'Coffee shop owner.', 'website_url' => 'https://grace-cafe.com',
                'zip' => '102-0071', 'address' => 'Shibuya, Tokyo', 'phonenumber' => '080-7777-7777',
                'instagram' => '@grace_cafe', 'facebook' => 'grace.fb', 'x' => '@grace_x', 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 8, 'name' => 'Heidi', 'email' => 'heidi@example.com',
                'avatar' => '/images/profile/heidi.jpg', 'header' => '/images/profile/8.jpg', 'password' => Hash::make('password'),
                'role_id' => 2, 'introduction' => 'Tour guide in Kyoto.', 'website_url' => 'https://kyoto-heidi.jp',
                'zip' => '600-0000', 'address' => 'Kyoto, Japan', 'phonenumber' => '080-8888-8888',
                'instagram' => '@heidi_tours', 'facebook' => null, 'x' => null, 'tiktok' => '@heidi_tok',
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 9, 'name' => 'Ivan', 'email' => 'ivan@example.com',
                'avatar' => '/images/profile/ivan.jpg', 'header' => '/images/profile/9.jpg', 'password' => Hash::make('password'),
                'role_id' => 2, 'introduction' => 'Hotel manager.', 'website_url' => 'https://ivanhotel.com',
                'zip' => '980-0001', 'address' => 'Sendai, Japan', 'phonenumber' => '080-9999-9999',
                'instagram' => null, 'facebook' => 'ivan.fb', 'x' => '@iv_x', 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 10, 'name' => 'Judy', 'email' => 'judy@example.com',
                'avatar' => '/images/profile/judy.jpg', 'header' => '/images/profile/10.jpg', 'password' => Hash::make('password'),
                'role_id' => 2, 'introduction' => 'Handmade crafts.', 'website_url' => 'https://judycrafts.com',
                'zip' => '370-0000', 'address' => 'Gunma, Japan', 'phonenumber' => '080-1234-0000',
                'instagram' => '@judy_handmade', 'facebook' => null, 'x' => null, 'tiktok' => '@judytok',
                'official_certification' => 3, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 11, 'name' => 'Mallory', 'email' => 'mallory@example.com',
                'avatar' => '/images/profile/mallory.jpg', 'header' => '/images/profile/11.jpg', 'password' => Hash::make('password'),
                'role_id' => 2, 'introduction' => 'Digital marketer.', 'website_url' => 'https://mallorymarketing.jp',
                'zip' => '810-0001', 'address' => 'Fukuoka, Japan', 'phonenumber' => '080-4567-1234',
                'instagram' => '@mallory_marketing', 'facebook' => 'mallory.fb', 'x' => null, 'tiktok' => null,
                'official_certification' => 3, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            [
                'id' => 12, 'name' => 'Niaj', 'email' => 'niaj@example.com',
                'avatar' => '/images/profile/niaj.jpg', 'header' => '/images/profile/12.jpg', 'password' => Hash::make('password'),
                'role_id' => 2, 'introduction' => null, 'website_url' => null,
                'zip' => '920-0001', 'address' => 'Kanazawa, Japan', 'phonenumber' => '080-3210-9999',
                'instagram' => null, 'facebook' => null, 'x' => '@niaj', 'tiktok' => null,
                'official_certification' => 3, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
            // Admin
            [
                'id' => 13, 'name' => 'admin', 'email' => 'admin@example.com',
                'avatar' => null, 'header' => null, 'password' => Hash::make('password'),
                'role_id' => 3, 'introduction' => null, 'website_url' => null,
                'zip' => '000-0000', 'address' => 'XXXXXXXXXXXXX', 'phonenumber' => '000-0000-0000',
                'instagram' => null, 'facebook' => null, 'x' => null, 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now()->subDays(rand(0, 30)), 'updated_at' => Carbon::now()->subDays(rand(0, 30)),
            ],
        ]);


        DB::table('businesses')->insert([
            [
                'id' => 1, 'user_id' => 7, 'name' => 'Shibuya Cafe',
                'main_image' => '/images/businesses/shibuya-cafe.jpg', 'introduction' => 'Trendy cafe in Shibuya.Trendy cafe in Shibuya.Trendy cafe in Shibuya.Trendy cafe in Shibuya.Trendy cafe in Shibuya.Trendy cafe in Shibuya.',
                'category_id' => 1, 'address_1' =>'東京都渋谷区道玄坂2-3-1 渋谷駅前ビル 2-3F', 'address_2' => 'Shibuya-ku', 'zip' => '150-0001',
                'phonenumber' => '080-1111-1111', 'email' => 'shibuya@cafe.com',
                'website_url' => 'https://shibucafe.jp', 'instagram' => '@shibucafe', 'facebook' => 'shibuya.fb', 'x' => '@shibuya_x',
                'tiktok' => '@shibuya_tok', 'official_certification' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2, 'user_id' => 8, 'name' => 'Kyoto Tour Desk',
                'main_image' => '/images/businesses/kyoto-tour.jpg', 'introduction' => 'Guided tours in Kyoto.Guided tours in Kyoto.Guided tours in Kyoto.Guided tours in Kyoto.Guided tours in Kyoto.Guided tours in Kyoto.',
                'category_id' => 1, 'address_1' => '京都府京都市南区東九条西山王町31 京都アバンティ B1F', 'address_2' => 'Nakagyo-ku', 'zip' => '604-0000',
                'phonenumber' => '080-2222-2222', 'email' => 'kyoto@tour.jp',
                'website_url' => null, 'instagram' => '@kyototours', 'facebook' => null, 'x' => null,
                'tiktok' => null, 'official_certification' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3, 'user_id' => 9, 'name' => 'Sendai Guesthouse',
                'main_image' => '/images/businesses/sendai-guesthouse.jpg', 'introduction' => 'Affordable stay in Sendai.Affordable stay in Sendai.Affordable stay in Sendai.Affordable stay in Sendai.Affordable stay in Sendai.Affordable stay in Sendai.',
                'category_id' => 1, 'address_1' => '宮城県仙台市宮城野区平成1-3-14', 'address_2' => 'Aoba-ku', 'zip' => '980-0001',
                'phonenumber' => '080-3333-3333', 'email' => 'stay@sendai.jp',
                'website_url' => 'https://sendai-guest.com', 'instagram' => null, 'facebook' => null, 'x' => null,
                'tiktok' => null, 'official_certification' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4, 'user_id' => 10, 'name' => 'Gunma Craft Shop',
                'main_image' => '/images/businesses/gunma-craft.jpg', 'introduction' => 'Handmade goods from Gunma.Handmade goods from Gunma.Handmade goods from Gunma.Handmade goods from Gunma.Handmade goods from Gunma.Handmade goods from Gunma.',
                'category_id' => 1, 'address_1' => '群馬県利根郡みなかみ町須川847 379-1418', 'address_2' => 'Takasaki', 'zip' => '370-0000',
                'phonenumber' => '080-4444-4444', 'email' => 'info@gunmacrafts.jp',
                'website_url' => 'https://gunmacrafts.jp', 'instagram' => '@gunma_shop', 'facebook' => null, 'x' => null,
                'tiktok' => null, 'official_certification' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5, 'user_id' => 11, 'name' => 'Fukuoka Marketing',
                'main_image' => '/images/businesses/fukuoka-marketing.jpg', 'introduction' => 'Local business marketing service.Local business marketing service.Local business marketing service.Local business marketing service.Local business marketing service.Local business marketing service.',
                'category_id' => 1, 'address_1' => '福岡県福岡市博多区博多駅前2丁目9-28 812-0011', 'address_2' => 'Chuo-ku', 'zip' => '810-0001',
                'phonenumber' => '080-5555-5555', 'email' => 'marketing@fukuoka.jp',
                'website_url' => null, 'instagram' => null, 'facebook' => 'fukuoka.biz', 'x' => null,
                'tiktok' => null, 'official_certification' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6, 'user_id' => 12, 'name' => 'Kanazawa Design Studio',
                'main_image' => '/images/businesses/kanazawa-design.jpg', 'introduction' => 'Modern design from Hokuriku.Modern design from Hokuriku.Modern design from Hokuriku.Modern design from Hokuriku.Modern design from Hokuriku.Modern design from Hokuriku.',
                'category_id' => 1, 'address_1' => '石川県金沢市菊川1-9-1 920-0967', 'address_2' => 'Higashi', 'zip' => '920-0001',
                'phonenumber' => '080-6666-6666', 'email' => 'hello@kanazawa.jp',
                'website_url' => 'https://kanazawastudio.jp', 'instagram' => '@kzstudio', 'facebook' => 'kanazawa.fb', 'x' => '@kzstudio',
                'tiktok' => null, 'official_certification' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7, 'user_id' => 7, 'name' => 'Shibuya Summer Fest',
                'main_image' => '/images/businesses/shibuya-summer-fest.jpg', 'introduction' => 'Annual summer event in Shibuya.Annual summer event in Shibuya.Annual summer event in Shibuya.Annual summer event in Shibuya.Annual summer event in Shibuya.Annual summer event in Shibuya.',
                'category_id' => 2, 'address_1' => '東京都渋谷区道玄坂2丁目（渋谷センター街周辺）', 'address_2' => 'Shibuya', 'zip' => '150-0001',
                'phonenumber' => '080-7777-1111', 'email' => 'event@shibuya.jp',
                'website_url' => 'https://shibufest.jp', 'instagram' => '@shibufest', 'facebook' => null, 'x' => '@shibufest',
                'tiktok' => '@shibufesttok', 'official_certification' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8, 'user_id' => 8, 'name' => 'Kyoto Cultural Night',
                'main_image' => '/images/businesses/kyoto-cultural-night.jpg', 'introduction' => 'Experience traditional Kyoto art.Experience traditional Kyoto art.Experience traditional Kyoto art.Experience traditional Kyoto art.Experience traditional Kyoto art.Experience traditional Kyoto art.',
                'category_id' => 2, 'address_1' => '京都府京都市下京区稲荷町318番6 600-8022', 'address_2' => 'Higashiyama', 'zip' => '605-0001',
                'phonenumber' => '080-8888-4444', 'email' => 'night@kyoto.jp',
                'website_url' => null, 'instagram' => '@kyotonight', 'facebook' => null, 'x' => '@kyotonight', 'tiktok' => null,
                'official_certification' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9, 'user_id' => 9, 'name' => 'Sendai Lights Festival',
                'main_image' => '/images/businesses/sendai-lights.jpg', 'introduction' => 'Beautiful winter lights in Sendai.Beautiful winter lights in Sendai.Beautiful winter lights in Sendai.Beautiful winter lights in Sendai.Beautiful winter lights in Sendai.Beautiful winter lights in Sendai.',
                'category_id' => 2, 'address_1' => '宮城県仙台市青葉区一番町4丁目11 定禅寺通り', 'address_2' => 'Aoba', 'zip' => '980-0021',
                'phonenumber' => '080-9999-5555', 'email' => 'light@sendai.jp',
                'website_url' => 'https://sendailights.jp', 'instagram' => '@sendailights', 'facebook' => 'sendai.fb',
                'x' => null, 'tiktok' => null, 'official_certification' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10, 'user_id' => 10, 'name' => 'Gunma Autumn Market',
                'main_image' => '/images/businesses/gunma-market.jpg', 'introduction' => 'Local food & crafts in Gunma.Local food & crafts in Gunma.Local food & crafts in Gunma.Local food & crafts in Gunma.Local food & crafts in Gunma.Local food & crafts in Gunma.',
                'category_id' => 2, 'address_1' => '群馬県利根郡昭和村糸井624 379-1204', 'address_2' => 'Maebashi', 'zip' => '370-1234',
                'phonenumber' => '080-1234-5678', 'email' => 'market@gunma.jp',
                'website_url' => null, 'instagram' => '@gunmamarket', 'facebook' => null, 'x' => null,
                'tiktok' => null, 'official_certification' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11, 'user_id' => 11, 'name' => 'Fukuoka Tech Expo',
                'main_image' => '/images/businesses/fukuoka-tech.jpg', 'introduction' => 'Latest in local tech innovation.Latest in local tech innovation.Latest in local tech innovation.Latest in local tech innovation.Latest in local tech innovation.Latest in local tech innovation.',
                'category_id' => 2, 'address_1' => '福岡県福岡市博多区沖浜町7-1 マリンメッセ福岡 812-0031', 'address_2' => 'Hakata', 'zip' => '812-0001',
                'phonenumber' => '080-5432-1234', 'email' => 'expo@fukuoka.jp',
                'website_url' => 'https://fukuokatech.jp', 'instagram' => '@fukuokatech', 'facebook' => null, 'x' => null,
                'tiktok' => '@fukuokatok', 'official_certification' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12, 'user_id' => 12, 'name' => 'Kanazawa Art Week',
                'main_image' => '/images/businesses/kanazawa-art.jpg', 'introduction' => 'Modern and traditional art exhibitions.Modern and traditional art exhibitions.Modern and traditional art exhibitions.Modern and traditional art exhibitions.Modern and traditional art exhibitions.Modern and traditional art exhibitions.',
                'category_id' => 2, 'address_1' => '石川県金沢市広坂1-2-1 920-8509', 'address_2' => 'Central', 'zip' => '920-0031',
                'phonenumber' => '080-9876-4321', 'email' => 'art@kanazawa.jp',
                'website_url' => null, 'instagram' => '@kzartweek', 'facebook' => 'kanazawa.fb', 'x' => null,
                'tiktok' => null, 'official_certification' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('business_promotions')->insert([
            [
                // 'id' => 1,
                'user_id' => 7,
                'business_id' => 1,
                'title' => 'Spring Coffee Campaign',
                'image' => '/images/businesses/promo-coffee.jpg',
                'introduction' => 'Buy 1 get 1 free on all coffees this spring!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 2,
                'user_id' => 8,
                'business_id' => 2,
                'title' => 'Kyoto Tour Discount',
                'image' => '/images/businesses/promo-tour.jpg',
                'introduction' => '20% off for early reservations.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 3,
                'user_id' => 9,
                'business_id' => 3,
                'title' => 'Guesthouse Opening Sale',
                'image' => '/images/businesses/promo-stay.jpg',
                'introduction' => 'First 100 guests stay free breakfast!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 4,
                'user_id' => 10,
                'business_id' => 4,
                'title' => 'Handmade Weekend Market',
                'image' => '/images/businesses/promo-market.jpg',
                'introduction' => 'Crafts festival with local artists.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 5,
                'user_id' => 11,
                'business_id' => 5,
                'title' => 'Startup Consultation Free',
                'image' => '/images/businesses/promo-business.jpg',
                'introduction' => 'First session free for new clients.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 6,
                'user_id' => 12,
                'business_id' => 6,
                'title' => 'Design Portfolio Free Review',
                'image' => '/images/businesses/promo-design.jpg',
                'introduction' => 'Submit your work and get feedback.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 7,
                'user_id' => 7,
                'business_id' => 7,
                'title' => 'Shibuya Fest Early Access',
                'image' => '/images/businesses/promo-fest.jpg',
                'introduction' => 'VIP tickets available now!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 8,
                'user_id' => 8,
                'business_id' => 8,
                'title' => 'Kyoto Culture Night Giveaway',
                'image' => '/images/businesses/promo-culture.jpg',
                'introduction' => 'Win traditional Japanese goods!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 9,
                'user_id' => 9,
                'business_id' => 9,
                'title' => 'Sendai Lights Photo Contest',
                'image' => '/images/businesses/promo-lights.jpg',
                'introduction' => 'Share your best shot for a prize.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 10,
                'user_id' => 10,
                'business_id' => 10,
                'title' => 'Autumn Market Bonus Points',
                'image' => '/images/businesses/promo-points.jpg',
                'introduction' => 'Earn double points on every purchase.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 11,
                'user_id' => 11,
                'business_id' => 11,
                'title' => 'Tech Expo Early Signup',
                'image' => '/images/businesses/promo-tech.jpg',
                'introduction' => 'Be the first to know!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // 'id' => 12,
                'user_id' => 12,
                'business_id' => 12,
                'title' => 'Art Week Workshop Seats',
                'image' => '/images/businesses/promo-art.jpg',
                'introduction' => 'Limited seats for live demos.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('business_comments')->insert([
            [
                'user_id' => 1,
                'business_id' => 3,
                'rating' => 5,
                'content' => 'Will definitely come again.',
                'created_at' => Carbon::parse('2025-03-27'),
                'updated_at' => Carbon::parse('2025-03-15'),
            ],
            [
                'user_id' => 7,
                'business_id' => 4,
                'rating' => 5,
                'content' => 'Highly recommended!',
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-03-13'),
            ],
            [
                'user_id' => 4,
                'business_id' => 7,
                'rating' => 3,
                'content' => 'Delicious food and quick service.',
                'created_at' => Carbon::parse('2025-03-24'),
                'updated_at' => Carbon::parse('2025-03-20'),
            ],
            [
                'user_id' => 3,
                'business_id' => 4,
                'rating' => 1,
                'content' => 'Delicious food and quick service.',
                'created_at' => Carbon::parse('2025-04-05'),
                'updated_at' => Carbon::parse('2025-03-18'),
            ],
            [
                'user_id' => 9,
                'business_id' => 2,
                'rating' => 2,
                'content' => 'Service could be better.',
                'created_at' => Carbon::parse('2025-03-15'),
                'updated_at' => Carbon::parse('2025-03-31'),
            ],
            [
                'user_id' => 8,
                'business_id' => 5,
                'rating' => 3,
                'content' => 'Will definitely come again.',
                'created_at' => Carbon::parse('2025-03-28'),
                'updated_at' => Carbon::parse('2025-03-26'),
            ],
            [
                'user_id' => 4,
                'business_id' => 3,
                'rating' => 3,
                'content' => 'Beautiful ambiance and decor.',
                'created_at' => Carbon::parse('2025-03-21'),
                'updated_at' => Carbon::parse('2025-03-30'),
            ],
            [
                'user_id' => 7,
                'business_id' => 1,
                'rating' => 3,
                'content' => 'Service could be better.',
                'created_at' => Carbon::parse('2025-03-31'),
                'updated_at' => Carbon::parse('2025-03-25'),
            ],
            [
                'user_id' => 8,
                'business_id' => 9,
                'rating' => 2,
                'content' => 'Perfect for a weekend visit.',
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-03-06'),
            ],
            [
                'user_id' => 5,
                'business_id' => 10,
                'rating' => 1,
                'content' => 'Staff was friendly and helpful.',
                'created_at' => Carbon::parse('2025-03-13'),
                'updated_at' => Carbon::parse('2025-03-14'),
            ],
            [
                'user_id' => 4,
                'business_id' => 6,
                'rating' => 1,
                'content' => 'Great place, loved it!',
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-03-08'),
            ],
            [
                'user_id' => 1,
                'business_id' => 3,
                'rating' => 3,
                'content' => 'Delicious food and quick service.',
                'created_at' => Carbon::parse('2025-03-14'),
                'updated_at' => Carbon::parse('2025-03-21'),
            ],
            [
                'user_id' => 5,
                'business_id' => 12,
                'rating' => 5,
                'content' => 'Overpriced for the quality.',
                'created_at' => Carbon::parse('2025-03-10'),
                'updated_at' => Carbon::parse('2025-03-23'),
            ],
            [
                'user_id' => 2,
                'business_id' => 10,
                'rating' => 5,
                'content' => 'Delicious food and quick service.',
                'created_at' => Carbon::parse('2025-03-31'),
                'updated_at' => Carbon::parse('2025-03-18'),
            ],
            [
                'user_id' => 1,
                'business_id' => 6,
                'rating' => 2,
                'content' => 'Will definitely come again.',
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-03-14'),
            ],
            [
                'user_id' => 11,
                'business_id' => 1,
                'rating' => 4,
                'content' => 'Perfect for a weekend visit.',
                'created_at' => Carbon::parse('2025-04-01'),
                'updated_at' => Carbon::parse('2025-03-17'),
            ],
            [
                'user_id' => 5,
                'business_id' => 10,
                'rating' => 1,
                'content' => 'Service could be better.',
                'created_at' => Carbon::parse('2025-03-09'),
                'updated_at' => Carbon::parse('2025-03-08'),
            ],
            [
                'user_id' => 2,
                'business_id' => 6,
                'rating' => 1,
                'content' => 'Overpriced for the quality.',
                'created_at' => Carbon::parse('2025-03-15'),
                'updated_at' => Carbon::parse('2025-03-29'),
            ],
            [
                'user_id' => 12,
                'business_id' => 11,
                'rating' => 5,
                'content' => 'Staff was friendly and helpful.',
                'created_at' => Carbon::parse('2025-03-20'),
                'updated_at' => Carbon::parse('2025-03-07'),
            ],
            [
                'user_id' => 4,
                'business_id' => 3,
                'rating' => 3,
                'content' => 'Highly recommended!',
                'created_at' => Carbon::parse('2025-03-14'),
                'updated_at' => Carbon::parse('2025-03-27'),
            ],
            [
                'user_id' => 4,
                'business_id' => 8,
                'rating' => 4,
                'content' => 'Perfect for a weekend visit.',
                'created_at' => Carbon::parse('2025-03-09'),
                'updated_at' => Carbon::parse('2025-03-14'),
            ],
            [
                'user_id' => 3,
                'business_id' => 11,
                'rating' => 1,
                'content' => 'Not what I expected.',
                'created_at' => Carbon::parse('2025-03-30'),
                'updated_at' => Carbon::parse('2025-03-07'),
            ],
            [
                'user_id' => 5,
                'business_id' => 3,
                'rating' => 5,
                'content' => 'Great place, loved it!',
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-03-31'),
            ],
            [
                'user_id' => 3,
                'business_id' => 11,
                'rating' => 2,
                'content' => 'Delicious food and quick service.',
                'created_at' => Carbon::parse('2025-03-13'),
                'updated_at' => Carbon::parse('2025-03-08'),
            ],
            [
                'user_id' => 6,
                'business_id' => 12,
                'rating' => 3,
                'content' => 'Beautiful ambiance and decor.',
                'created_at' => Carbon::parse('2025-03-08'),
                'updated_at' => Carbon::parse('2025-03-12'),
            ],
            [
                'user_id' => 3,
                'business_id' => 1,
                'rating' => 3,
                'content' => 'Will definitely come again.',
                'created_at' => Carbon::parse('2025-03-23'),
                'updated_at' => Carbon::parse('2025-03-27'),
            ],
            [
                'user_id' => 4,
                'business_id' => 9,
                'rating' => 3,
                'content' => 'Service could be better.',
                'created_at' => Carbon::parse('2025-03-09'),
                'updated_at' => Carbon::parse('2025-03-09'),
            ],
            [
                'user_id' => 9,
                'business_id' => 2,
                'rating' => 4,
                'content' => 'Highly recommended!',
                'created_at' => Carbon::parse('2025-04-01'),
                'updated_at' => Carbon::parse('2025-03-21'),
            ],
            [
                'user_id' => 10,
                'business_id' => 5,
                'rating' => 2,
                'content' => 'Overpriced for the quality.',
                'created_at' => Carbon::parse('2025-03-10'),
                'updated_at' => Carbon::parse('2025-03-08'),
            ],
        ]);

        DB::table('spots')->insert([
            [
                'user_id' => 2,
                'title' => 'Mount Fuji Viewpoint',
                'main_image' => '/images/spots/fuji.jpg',
                'introduction' => 'A breathtaking spot with scenic views.A breathtaking spot with scenic views.A breathtaking spot with scenic views.A breathtaking spot with scenic views.',
                'geo_location' => null,
                'geo_lat' => 35.5175,
                'geo_lng' => 138.7594,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-21'),
                'updated_at' => Carbon::parse('2025-03-26'),
            ],
            [
                'user_id' => 7,
                'title' => 'Tokyo Skytree',
                'main_image' => '/images/spots/skytree.jpg',
                'introduction' => 'A popular tourist attraction with modern appeal.A popular tourist attraction with modern appeal.A popular tourist attraction with modern appeal.A popular tourist attraction with modern appeal.A popular tourist attraction with modern appeal.',
                'geo_location' => null,
                'geo_lat' => 35.7100,
                'geo_lng' => 139.8107,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-28'),
                'updated_at' => Carbon::parse('2025-03-14'),
            ],
            [
                'user_id' => 11,
                'title' => 'Kyoto Bamboo Forest',
                'main_image' => '/images/spots/bamboo.jpg',
                'introduction' => 'Experience the beauty of nature and tradition.Experience the beauty of nature and tradition.Experience the beauty of nature and tradition.Experience the beauty of nature and tradition.',
                'geo_location' => null,
                'geo_lat' => 35.0094,
                'geo_lng' => 135.6675,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-22'),
                'updated_at' => Carbon::parse('2025-03-30'),
            ],
            [
                'user_id' => 8,
                'title' => 'Osaka Castle Park',
                'main_image' => '/images/spots/osaka-castle.jpg',
                'introduction' => 'Perfect for a relaxing day trip.Perfect for a relaxing day trip.Perfect for a relaxing day trip.Perfect for a relaxing day trip.',
                'geo_location' => null,
                'geo_lat' => 34.6873,
                'geo_lng' => 135.5262,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-11'),
                'updated_at' => Carbon::parse('2025-03-24'),
            ],
            [
                'user_id' => 3,
                'title' => 'Nara Deer Park',
                'main_image' => '/images/spots/nara.jpg',
                'introduction' => 'Enjoy feeding the friendly deer!Enjoy feeding the friendly deer!Enjoy feeding the friendly deer!Enjoy feeding the friendly deer!Enjoy feeding the friendly deer!',
                'geo_location' => null,
                'geo_lat' => 34.6851,
                'geo_lng' => 135.8431,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-31'),
                'updated_at' => Carbon::parse('2025-03-20'),
            ],
            [
                'user_id' => 6,
                'title' => 'Hiroshima Peace Memorial',
                'main_image' => '/images/spots/hiroshima.jpg',
                'introduction' => 'Learn about history in a peaceful setting.Learn about history in a peaceful setting.Learn about history in a peaceful setting.Learn about history in a peaceful setting.',
                'geo_location' => null,
                'geo_lat' => 34.3955,
                'geo_lng' => 132.4536,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-25'),
                'updated_at' => Carbon::parse('2025-03-12'),
            ],
            [
                'user_id' => 12,
                'title' => 'Okinawa Beachside',
                'main_image' => '/images/spots/okinawa.jpg',
                'introduction' => 'Crystal clear waters and sandy beaches.Crystal clear waters and sandy beaches.Crystal clear waters and sandy beaches.Crystal clear waters and sandy beaches.Crystal clear waters and sandy beaches.',
                'geo_location' => null,
                'geo_lat' => 26.3225,
                'geo_lng' => 127.7550,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-18'),
                'updated_at' => Carbon::parse('2025-03-21'),
            ],
            [
                'user_id' => 10,
                'title' => 'Nagoya Castle',
                'main_image' => '/images/spots/nagoya.jpg',
                'introduction' => 'Historic architecture and lovely gardens.Historic architecture and lovely gardens.Historic architecture and lovely gardens.Historic architecture and lovely gardens.Historic architecture and lovely gardens.',
                'geo_location' => null,
                'geo_lat' => 35.1850,
                'geo_lng' => 136.8990,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-10'),
                'updated_at' => Carbon::parse('2025-03-17'),
            ],
            [
                'user_id' => 9,
                'title' => 'Hakone Hot Springs',
                'main_image' => '/images/spots/hakone.jpg',
                'introduction' => 'Famous for relaxing hot springs.Famous for relaxing hot springs.Famous for relaxing hot springs.Famous for relaxing hot springs.Famous for relaxing hot springs.',
                'geo_location' => null,
                'geo_lat' => 35.2333,
                'geo_lng' => 139.1056,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-08'),
                'updated_at' => Carbon::parse('2025-03-23'),
            ],
            [
                'user_id' => 4,
                'title' => 'Shibuya Crossing',
                'main_image' => '/images/spots/shibuya.jpg',
                'introduction' => 'Busy, vibrant, and full of energy!Busy, vibrant, and full of energy!Busy, vibrant, and full of energy!Busy, vibrant, and full of energy!Busy, vibrant, and full of energy!',
                'geo_location' => null,
                'geo_lat' => 35.6595,
                'geo_lng' => 139.7005,
                'images' => null,
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-03-19'),
            ],
            [
                'user_id' => 5,
                'title' => 'Ghibli Museum',
                'main_image' => '/images/spots/ghibli.jpg',
                'introduction' => 'For fans of anime and film lovers.For fans of anime and film lovers.For fans of anime and film lovers.For fans of anime and film lovers.For fans of anime and film lovers.',
                'geo_location' => null,
                'geo_lat' => 35.6962,
                'geo_lng' => 139.5703,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-29'),
                'updated_at' => Carbon::parse('2025-03-10'),
            ],
            [
                'user_id' => 1,
                'title' => 'Kobe Harborland',
                'main_image' => '/images/spots/kobe.jpg',
                'introduction' => 'Great shopping and seaside views.Great shopping and seaside views.Great shopping and seaside views.Great shopping and seaside views.Great shopping and seaside views.',
                'geo_location' => null,
                'geo_lat' => 34.6784,
                'geo_lng' => 135.1799,
                'images' => null,
                'created_at' => Carbon::parse('2025-03-14'),
                'updated_at' => Carbon::parse('2025-03-27'),
            ],
        ]);

        DB::table('spot_likes')->insert([
            ['user_id' => 12, 'spot_id' => 4],
            ['user_id' => 3,  'spot_id' => 7],
            ['user_id' => 9,  'spot_id' => 5],
            ['user_id' => 8,  'spot_id' => 6],
            ['user_id' => 2,  'spot_id' => 2],
            ['user_id' => 1,  'spot_id' => 11],
            ['user_id' => 4,  'spot_id' => 12],
            ['user_id' => 3,  'spot_id' => 2],
            ['user_id' => 10, 'spot_id' => 10],
            ['user_id' => 2,  'spot_id' => 5],
            ['user_id' => 7,  'spot_id' => 9],
            ['user_id' => 5,  'spot_id' => 12],
            ['user_id' => 4,  'spot_id' => 6],
            ['user_id' => 6,  'spot_id' => 2],
            ['user_id' => 1,  'spot_id' => 3],
            ['user_id' => 11, 'spot_id' => 10],
            ['user_id' => 9,  'spot_id' => 8],
            ['user_id' => 6,  'spot_id' => 3],
            ['user_id' => 10, 'spot_id' => 11],
            ['user_id' => 8,  'spot_id' => 1],
            ['user_id' => 11, 'spot_id' => 7],
            ['user_id' => 5,  'spot_id' => 6],
            ['user_id' => 12, 'spot_id' => 9],
            ['user_id' => 4,  'spot_id' => 4],
            ['user_id' => 2,  'spot_id' => 1],
            ['user_id' => 7,  'spot_id' => 8],
            ['user_id' => 1,  'spot_id' => 5],
            ['user_id' => 10, 'spot_id' => 2],
            ['user_id' => 6,  'spot_id' => 12],
            ['user_id' => 9,  'spot_id' => 10],
        ]);


        DB::table('spot_comments')->insert([
            [
                'user_id' => 9,
                'spot_id' => 1,
                'content' => 'Perfect spot for a picnic.',
                'created_at' => Carbon::parse('2025-03-30'),
                'updated_at' => Carbon::parse('2025-03-07'),
            ],
            [
                'user_id' => 5,
                'spot_id' => 12,
                'content' => 'Not much to see, but okay.',
                'created_at' => Carbon::parse('2025-03-23'),
                'updated_at' => Carbon::parse('2025-03-25'),
            ],
            [
                'user_id' => 5,
                'spot_id' => 4,
                'content' => 'Absolutely loved this spot!',
                'created_at' => Carbon::parse('2025-03-07'),
                'updated_at' => Carbon::parse('2025-03-20'),
            ],
            [
                'user_id' => 5,
                'spot_id' => 9,
                'content' => 'A bit hard to find but beautiful.',
                'created_at' => Carbon::parse('2025-03-09'),
                'updated_at' => Carbon::parse('2025-04-03'),
            ],
            [
                'user_id' => 6,
                'spot_id' => 3,
                'content' => 'Absolutely loved this spot!',
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-04-02'),
            ],
            [
                'user_id' => 11,
                'spot_id' => 2,
                'content' => 'Good for a short walk and chill.',
                'created_at' => Carbon::parse('2025-03-29'),
                'updated_at' => Carbon::parse('2025-03-17'),
            ],
            [
                'user_id' => 7,
                'spot_id' => 8,
                'content' => 'Too crowded but worth visiting.',
                'created_at' => Carbon::parse('2025-03-18'),
                'updated_at' => Carbon::parse('2025-03-30'),
            ],
            [
                'user_id' => 3,
                'spot_id' => 1,
                'content' => 'Amazing place to take pictures.',
                'created_at' => Carbon::parse('2025-03-16'),
                'updated_at' => Carbon::parse('2025-03-25'),
            ],
            [
                'user_id' => 2,
                'spot_id' => 6,
                'content' => 'Clean and well maintained.',
                'created_at' => Carbon::parse('2025-03-13'),
                'updated_at' => Carbon::parse('2025-03-30'),
            ],
            [
                'user_id' => 10,
                'spot_id' => 5,
                'content' => 'I would come again!',
                'created_at' => Carbon::parse('2025-03-28'),
                'updated_at' => Carbon::parse('2025-03-12'),
            ],
            [
                'user_id' => 10,
                'spot_id' => 10,
                'content' => 'Clean and well maintained.',
                'created_at' => Carbon::parse('2025-03-08'),
                'updated_at' => Carbon::parse('2025-03-27'),
            ],
            [
                'user_id' => 7,
                'spot_id' => 9,
                'content' => 'A bit hard to find but beautiful.',
                'created_at' => Carbon::parse('2025-04-03'),
                'updated_at' => Carbon::parse('2025-03-15'),
            ],
            [
                'user_id' => 12,
                'spot_id' => 8,
                'content' => 'Too crowded but worth visiting.',
                'created_at' => Carbon::parse('2025-03-10'),
                'updated_at' => Carbon::parse('2025-03-14'),
            ],
            [
                'user_id' => 11,
                'spot_id' => 5,
                'content' => 'Good for a short walk and chill.',
                'created_at' => Carbon::parse('2025-03-24'),
                'updated_at' => Carbon::parse('2025-03-17'),
            ],
            [
                'user_id' => 4,
                'spot_id' => 7,
                'content' => 'Perfect spot for a picnic.',
                'created_at' => Carbon::parse('2025-03-15'),
                'updated_at' => Carbon::parse('2025-03-30'),
            ],
            [
                'user_id' => 1,
                'spot_id' => 6,
                'content' => 'Not much to see, but okay.',
                'created_at' => Carbon::parse('2025-03-30'),
                'updated_at' => Carbon::parse('2025-03-09'),
            ],
            [
                'user_id' => 4,
                'spot_id' => 3,
                'content' => 'Absolutely loved this spot!',
                'created_at' => Carbon::parse('2025-03-16'),
                'updated_at' => Carbon::parse('2025-03-21'),
            ],
            [
                'user_id' => 8,
                'spot_id' => 12,
                'content' => 'Amazing place to take pictures.',
                'created_at' => Carbon::parse('2025-03-26'),
                'updated_at' => Carbon::parse('2025-03-29'),
            ],
            [
                'user_id' => 6,
                'spot_id' => 2,
                'content' => 'Great views and peaceful atmosphere.',
                'created_at' => Carbon::parse('2025-03-11'),
                'updated_at' => Carbon::parse('2025-03-16'),
            ],
            [
                'user_id' => 9,
                'spot_id' => 11,
                'content' => 'Clean and well maintained.',
                'created_at' => Carbon::parse('2025-03-24'),
                'updated_at' => Carbon::parse('2025-03-11'),
            ],
            [
                'user_id' => 2,
                'spot_id' => 3,
                'content' => 'Too crowded but worth visiting.',
                'created_at' => Carbon::parse('2025-03-28'),
                'updated_at' => Carbon::parse('2025-03-27'),
            ],
            [
                'user_id' => 11,
                'spot_id' => 10,
                'content' => 'Good for a short walk and chill.',
                'created_at' => Carbon::parse('2025-03-21'),
                'updated_at' => Carbon::parse('2025-03-15'),
            ],
            [
                'user_id' => 3,
                'spot_id' => 6,
                'content' => 'Perfect spot for a picnic.',
                'created_at' => Carbon::parse('2025-03-13'),
                'updated_at' => Carbon::parse('2025-03-10'),
            ],
            [
                'user_id' => 3,
                'spot_id' => 12,
                'content' => 'Amazing place to take pictures.',
                'created_at' => Carbon::parse('2025-03-08'),
                'updated_at' => Carbon::parse('2025-03-08'),
            ],
            [
                'user_id' => 1,
                'spot_id' => 7,
                'content' => 'Great views and peaceful atmosphere.',
                'created_at' => Carbon::parse('2025-03-17'),
                'updated_at' => Carbon::parse('2025-03-25'),
            ],
            [
                'user_id' => 2,
                'spot_id' => 8,
                'content' => 'Clean and well maintained.',
                'created_at' => Carbon::parse('2025-03-15'),
                'updated_at' => Carbon::parse('2025-03-14'),
            ],
            [
                'user_id' => 8,
                'spot_id' => 4,
                'content' => 'Not much to see, but okay.',
                'created_at' => Carbon::parse('2025-03-30'),
                'updated_at' => Carbon::parse('2025-03-26'),
            ],
            [
                'user_id' => 7,
                'spot_id' => 3,
                'content' => 'Too crowded but worth visiting.',
                'created_at' => Carbon::parse('2025-03-22'),
                'updated_at' => Carbon::parse('2025-03-22'),
            ],
            [
                'user_id' => 10,
                'spot_id' => 1,
                'content' => 'Absolutely loved this spot!',
                'created_at' => Carbon::parse('2025-03-19'),
                'updated_at' => Carbon::parse('2025-03-20'),
            ],
            [
                'user_id' => 12,
                'spot_id' => 4,
                'content' => 'Perfect spot for a picnic.',
                'created_at' => Carbon::parse('2025-03-12'),
                'updated_at' => Carbon::parse('2025-03-28'),
            ],
        ]);

        DB::table('spot_comment_likes')->insert([
            ['user_id' => 3, 'spot_comment_id' => 1],
            ['user_id' => 12, 'spot_comment_id' => 19],
            ['user_id' => 10, 'spot_comment_id' => 6],
            ['user_id' => 2, 'spot_comment_id' => 2],
            ['user_id' => 5, 'spot_comment_id' => 25],
            ['user_id' => 8, 'spot_comment_id' => 16],
            ['user_id' => 1, 'spot_comment_id' => 14],
            ['user_id' => 6, 'spot_comment_id' => 13],
            ['user_id' => 11, 'spot_comment_id' => 30],
            ['user_id' => 7, 'spot_comment_id' => 7],
            ['user_id' => 9, 'spot_comment_id' => 24],
            ['user_id' => 4, 'spot_comment_id' => 20],
            ['user_id' => 2, 'spot_comment_id' => 10],
            ['user_id' => 12, 'spot_comment_id' => 9],
            ['user_id' => 1, 'spot_comment_id' => 4],
            ['user_id' => 5, 'spot_comment_id' => 17],
            ['user_id' => 3, 'spot_comment_id' => 5],
            ['user_id' => 8, 'spot_comment_id' => 27],
            ['user_id' => 11, 'spot_comment_id' => 28],
            ['user_id' => 6, 'spot_comment_id' => 11],
            ['user_id' => 10, 'spot_comment_id' => 18],
            ['user_id' => 7, 'spot_comment_id' => 21],
            ['user_id' => 9, 'spot_comment_id' => 26],
            ['user_id' => 4, 'spot_comment_id' => 8],
            ['user_id' => 2, 'spot_comment_id' => 12],
            ['user_id' => 1, 'spot_comment_id' => 3],
            ['user_id' => 3, 'spot_comment_id' => 22],
            ['user_id' => 10, 'spot_comment_id' => 15],
            ['user_id' => 5, 'spot_comment_id' => 29],
            ['user_id' => 8, 'spot_comment_id' => 23],
        ]);

        DB::table('business_comment_likes')->insert([
            ['user_id' => 12, 'business_comment_id' => 4],
            ['user_id' => 12, 'business_comment_id' => 7],
            ['user_id' => 7,  'business_comment_id' => 25],
            ['user_id' => 5,  'business_comment_id' => 13],
            ['user_id' => 4,  'business_comment_id' => 18],
            ['user_id' => 6,  'business_comment_id' => 9],
            ['user_id' => 11, 'business_comment_id' => 3],
            ['user_id' => 9,  'business_comment_id' => 2],
            ['user_id' => 8,  'business_comment_id' => 17],
            ['user_id' => 10, 'business_comment_id' => 6],
            ['user_id' => 1,  'business_comment_id' => 1],
            ['user_id' => 2,  'business_comment_id' => 5],
            ['user_id' => 3,  'business_comment_id' => 8],
            ['user_id' => 6,  'business_comment_id' => 19],
            ['user_id' => 5,  'business_comment_id' => 11],
            ['user_id' => 4,  'business_comment_id' => 22],
            ['user_id' => 9,  'business_comment_id' => 15],
            ['user_id' => 7,  'business_comment_id' => 23],
            ['user_id' => 10, 'business_comment_id' => 13],
            ['user_id' => 11, 'business_comment_id' => 14],
            ['user_id' => 2,  'business_comment_id' => 24],
            ['user_id' => 8,  'business_comment_id' => 12],
            ['user_id' => 3,  'business_comment_id' => 10],
            ['user_id' => 1,  'business_comment_id' => 16],
            ['user_id' => 6,  'business_comment_id' => 18],
            ['user_id' => 9,  'business_comment_id' => 25],
            ['user_id' => 12, 'business_comment_id' => 20],
            ['user_id' => 7,  'business_comment_id' => 17],
            ['user_id' => 4,  'business_comment_id' => 21],
            ['user_id' => 5,  'business_comment_id' => 9],
        ]);

        DB::table('follows')->insert([
            ['follower_id' => 12, 'followed_id' => 7],
            ['follower_id' => 4,  'followed_id' => 6],
            ['follower_id' => 5,  'followed_id' => 1],
            ['follower_id' => 8,  'followed_id' => 3],
            ['follower_id' => 11, 'followed_id' => 5],
            ['follower_id' => 6,  'followed_id' => 1],
            ['follower_id' => 2,  'followed_id' => 7],
            ['follower_id' => 7,  'followed_id' => 4],
            ['follower_id' => 9,  'followed_id' => 10],
            ['follower_id' => 10, 'followed_id' => 2],
            ['follower_id' => 3,  'followed_id' => 12],
            ['follower_id' => 1,  'followed_id' => 11],
            ['follower_id' => 8,  'followed_id' => 5],
            ['follower_id' => 6,  'followed_id' => 4],
            ['follower_id' => 5,  'followed_id' => 9],
            ['follower_id' => 2,  'followed_id' => 10],
            ['follower_id' => 7,  'followed_id' => 3],
            ['follower_id' => 9,  'followed_id' => 6],
            ['follower_id' => 10, 'followed_id' => 1],
            ['follower_id' => 3,  'followed_id' => 8],
            ['follower_id' => 1,  'followed_id' => 6],
            ['follower_id' => 11, 'followed_id' => 4],
            ['follower_id' => 12, 'followed_id' => 2],
            ['follower_id' => 4,  'followed_id' => 8],
            ['follower_id' => 6,  'followed_id' => 10],
            ['follower_id' => 5,  'followed_id' => 7],
            ['follower_id' => 8,  'followed_id' => 9],
            ['follower_id' => 10, 'followed_id' => 11],
            ['follower_id' => 9,  'followed_id' => 2],
            ['follower_id' => 7,  'followed_id' => 12],
        ]);


        DB::table('quests')->insert([
            [
                'user_id' => 6,
                'title' => 'Discover Kyoto Temples',
                'main_image' => '/images/quests/quest-kyoto.jpg',
                'introduction' => 'Explore the ancient temples of Kyoto and uncover their secrets.',
                'start_date' => '2022-01-10', 
                'end_date' => '2022-01-12',
                'duration' => null,
                'is_public' => false,
                'created_at' => Carbon::parse('2025-03-09'),
                'updated_at' => Carbon::parse('2025-03-29'),
            ],
            [
                'user_id' => 3,
                'title' => 'Tokyo Street Food Hunt',
                'main_image' => '/images/quests/quest-tokyo.jpg',
                'introduction' => "Taste your way through Tokyo's bustling street food scene.",
                'start_date' => '2022-02-05',
                'end_date' => '2022-02-09',
                'duration' => null,
                'is_public' => true,
                'created_at' => Carbon::parse('2025-03-21'),
                'updated_at' => Carbon::parse('2025-03-18'),
            ],
            [
                'user_id' => 2,
                'title' => 'Okinawa Beach Adventure',
                'main_image' => '/images/quests/quest-okinawa.jpg',
                'introduction' => 'Relax and discover hidden beaches in Okinawa.',
                'start_date' => '2022-03-15',
                'end_date' => '2022-03-18',
                'duration' => null,
                'is_public' => false,
                'created_at' => Carbon::parse('2025-03-14'),
                'updated_at' => Carbon::parse('2025-03-28'),
            ],
            [
                'user_id' => 8,
                'title' => 'Historic Nara Walk',
                'main_image' => '/images/quests/quest-nara.jpg',
                'introduction' => 'Walk with the deer and visit heritage sites in Nara.',
                'start_date' => null,
                'end_date' => null,
                'duration' => 2,
                'is_public' => true,
                'created_at' => Carbon::parse('2025-04-02'),
                'updated_at' => Carbon::parse('2025-03-31'),
            ],
            [
                'user_id' => 6,
                'title' => 'Osaka Nightlife Quest',
                'main_image' => '/images/quests/quest-osaka.jpg',
                'introduction' => 'Experience Osaka’s vibrant nightlife like a local.',
                'start_date' => '2023-04-01',
                'end_date' => '2023-04-07',
                'duration' => null,
                'is_public' => false,
                'created_at' => Carbon::parse('2025-03-25'),
                'updated_at' => Carbon::parse('2025-04-03'),
            ],
            [
                'user_id' => 11,
                'title' => 'Shizuoka Green Tea Trail',
                'main_image' => '/images/quests/quest-shizuoka.jpg',
                'introduction' => 'Learn about green tea production in scenic Shizuoka.',
                'start_date' => null,
                'end_date' => null,
                'duration' => 1,
                'is_public' => false,
                'created_at' => Carbon::parse('2025-03-26'),
                'updated_at' => Carbon::parse('2025-03-13'),
            ],
            [
                'user_id' => 5,
                'title' => 'Mount Fuji Challenge',
                'main_image' => '/images/quests/quest-fuji.jpg',
                'introduction' => 'Take on the adventure to climb Mount Fuji.',
                'start_date' => '2024-05-20',
                'end_date' => '2024-05-23',
                'duration' => null,
                'is_public' => true,
                'created_at' => Carbon::parse('2025-03-28'),
                'updated_at' => Carbon::parse('2025-03-14'),
            ],
            [
                'user_id' => 10,
                'title' => 'Hokkaido Nature Quest',
                'main_image' => '/images/quests/quest-hokkaido.jpg',
                'introduction' => "Wander through Hokkaido's untouched nature trails.",
                'start_date' => null,
                'end_date' => null,
                'duration' => 3,
                'is_public' => true,
                'created_at' => Carbon::parse('2025-03-18'),
                'updated_at' => Carbon::parse('2025-03-19'),
            ],
            [
                'user_id' => 9,
                'title' => 'Nagano Snow Trek',
                'main_image' => '/images/quests/quest-nagano.jpg',
                'introduction' => 'Enjoy the snowy mountains and peaceful landscapes of Nagano.',
                'start_date' => null,
                'end_date' => null,
                'duration' => 1,
                'is_public' => true,
                'created_at' => Carbon::parse('2025-03-13'),
                'updated_at' => Carbon::parse('2025-03-26'),
            ],
            [
                'user_id' => 4,
                'title' => 'Fukuoka Ramen Tour',
                'main_image' => '/images/quests/quest-fukuoka.jpg',
                'introduction' => 'Slurp your way through the best ramen shops in Fukuoka.',
                'start_date' => '2024-06-11',
                'end_date' => '2024-06-13',
                'duration' => null,
                'is_public' => false,
                'created_at' => Carbon::parse('2025-03-30'),
                'updated_at' => Carbon::parse('2025-03-22'),
            ],
            [
                'user_id' => 7,
                'title' => 'Art in Kanazawa',
                'main_image' => '/images/quests/quest-kanazawa.jpg',
                'introduction' => 'Dive into the art and culture scene of Kanazawa.',
                'start_date' => null,
                'end_date' => null,
                'duration' => 2,
                'is_public' => true,
                'created_at' => Carbon::parse('2025-03-08'),
                'updated_at' => Carbon::parse('2025-03-31'),
            ],
            [
                'user_id' => 1,
                'title' => 'Kobe Port Exploration',
                'main_image' => '/images/quests/quest-kobe.jpg',
                'introduction' => 'Discover Kobe’s beautiful harbor and maritime history.',
                'start_date' => '2022-07-03',
                'end_date' => '2022-07-08',
                'duration' => null,
                'is_public' => false,
                'created_at' => Carbon::parse('2025-03-24'),
                'updated_at' => Carbon::parse('2025-03-21'),
            ],
        ]);


        DB::table('quest_likes')->insert([
            ['user_id' => 12, 'quest_id' => 7],
            ['user_id' => 5,  'quest_id' => 4],
            ['user_id' => 3,  'quest_id' => 10],
            ['user_id' => 11, 'quest_id' => 2],
            ['user_id' => 5,  'quest_id' => 10],
            ['user_id' => 9,  'quest_id' => 9],
            ['user_id' => 4,  'quest_id' => 8],
            ['user_id' => 11, 'quest_id' => 8],
            ['user_id' => 6,  'quest_id' => 12],
            ['user_id' => 10, 'quest_id' => 7],
            ['user_id' => 7,  'quest_id' => 1],
            ['user_id' => 9,  'quest_id' => 12],
            ['user_id' => 2,  'quest_id' => 8],
            ['user_id' => 1,  'quest_id' => 11],
            ['user_id' => 8,  'quest_id' => 10],
            ['user_id' => 6,  'quest_id' => 6],
            ['user_id' => 8,  'quest_id' => 11],
            ['user_id' => 2,  'quest_id' => 5],
            ['user_id' => 7,  'quest_id' => 10],
            ['user_id' => 4,  'quest_id' => 11],
            ['user_id' => 12, 'quest_id' => 1],
            ['user_id' => 1,  'quest_id' => 4],
            ['user_id' => 7,  'quest_id' => 9],
            ['user_id' => 11, 'quest_id' => 9],
            ['user_id' => 3,  'quest_id' => 7],
            ['user_id' => 10, 'quest_id' => 2],
            ['user_id' => 6,  'quest_id' => 9],
            ['user_id' => 8,  'quest_id' => 6],
            ['user_id' => 9,  'quest_id' => 2],
            ['user_id' => 2,  'quest_id' => 7],
        ]);


        DB::table('quest_comments')->insert([
            ['user_id' => 9,  'quest_id' => 11, 'content' => 'Great for first-time travelers!', 'created_at' => Carbon::parse('2025-04-02'), 'updated_at' => Carbon::parse('2025-03-11')],
            ['user_id' => 4,  'quest_id' => 2,  'content' => 'Great for first-time travelers!', 'created_at' => Carbon::parse('2025-04-02'), 'updated_at' => Carbon::parse('2025-03-22')],
            ['user_id' => 2,  'quest_id' => 3,  'content' => 'Loved the cultural experience.',   'created_at' => Carbon::parse('2025-03-31'), 'updated_at' => Carbon::parse('2025-03-29')],
            ['user_id' => 8,  'quest_id' => 4,  'content' => 'Great for first-time travelers!', 'created_at' => Carbon::parse('2025-03-27'), 'updated_at' => Carbon::parse('2025-04-01')],
            ['user_id' => 9,  'quest_id' => 12, 'content' => 'This quest was so much fun!',     'created_at' => Carbon::parse('2025-03-28'), 'updated_at' => Carbon::parse('2025-04-03')],
            ['user_id' => 3,  'quest_id' => 1,  'content' => 'Really enjoyed exploring this route.', 'created_at' => Carbon::parse('2025-03-21'), 'updated_at' => Carbon::parse('2025-03-29')],
            ['user_id' => 6,  'quest_id' => 8,  'content' => 'A bit tiring, but totally worth it.',  'created_at' => Carbon::parse('2025-03-10'), 'updated_at' => Carbon::parse('2025-03-25')],
            ['user_id' => 5,  'quest_id' => 10, 'content' => 'Nice scenery and good pacing.',        'created_at' => Carbon::parse('2025-03-26'), 'updated_at' => Carbon::parse('2025-03-15')],
            ['user_id' => 10, 'quest_id' => 9,  'content' => 'Challenging but rewarding!',           'created_at' => Carbon::parse('2025-03-09'), 'updated_at' => Carbon::parse('2025-04-02')],
            ['user_id' => 1,  'quest_id' => 6,  'content' => 'Beautiful spots and easy to follow.',  'created_at' => Carbon::parse('2025-03-15'), 'updated_at' => Carbon::parse('2025-03-30')],
            ['user_id' => 2,  'quest_id' => 2,  'content' => 'I learned a lot from this journey.',   'created_at' => Carbon::parse('2025-03-24'), 'updated_at' => Carbon::parse('2025-03-25')],
            ['user_id' => 7,  'quest_id' => 5,  'content' => 'This quest was so much fun!',          'created_at' => Carbon::parse('2025-03-18'), 'updated_at' => Carbon::parse('2025-03-28')],
            ['user_id' => 11, 'quest_id' => 7,  'content' => 'Nice scenery and good pacing.',        'created_at' => Carbon::parse('2025-03-13'), 'updated_at' => Carbon::parse('2025-03-26')],
            ['user_id' => 12, 'quest_id' => 11, 'content' => 'Loved the cultural experience.',       'created_at' => Carbon::parse('2025-03-20'), 'updated_at' => Carbon::parse('2025-03-31')],
            ['user_id' => 8,  'quest_id' => 3,  'content' => 'Would recommend to anyone visiting.',  'created_at' => Carbon::parse('2025-03-30'), 'updated_at' => Carbon::parse('2025-03-19')],
            ['user_id' => 5,  'quest_id' => 1,  'content' => 'Great for first-time travelers!',      'created_at' => Carbon::parse('2025-03-31'), 'updated_at' => Carbon::parse('2025-03-30')],
            ['user_id' => 6,  'quest_id' => 12, 'content' => 'Really enjoyed exploring this route.', 'created_at' => Carbon::parse('2025-04-01'), 'updated_at' => Carbon::parse('2025-03-22')],
            ['user_id' => 9,  'quest_id' => 8,  'content' => 'Challenging but rewarding!',           'created_at' => Carbon::parse('2025-03-11'), 'updated_at' => Carbon::parse('2025-03-12')],
            ['user_id' => 3,  'quest_id' => 5,  'content' => 'I learned a lot from this journey.',   'created_at' => Carbon::parse('2025-03-29'), 'updated_at' => Carbon::parse('2025-03-18')],
            ['user_id' => 4,  'quest_id' => 7,  'content' => 'This quest was so much fun!',          'created_at' => Carbon::parse('2025-03-14'), 'updated_at' => Carbon::parse('2025-03-16')],
            ['user_id' => 1,  'quest_id' => 4,  'content' => 'Would recommend to anyone visiting.',  'created_at' => Carbon::parse('2025-03-23'), 'updated_at' => Carbon::parse('2025-03-21')],
            ['user_id' => 10, 'quest_id' => 9,  'content' => 'Nice scenery and good pacing.',        'created_at' => Carbon::parse('2025-03-26'), 'updated_at' => Carbon::parse('2025-03-30')],
            ['user_id' => 2,  'quest_id' => 6,  'content' => 'Beautiful spots and easy to follow.',  'created_at' => Carbon::parse('2025-03-28'), 'updated_at' => Carbon::parse('2025-03-27')],
            ['user_id' => 12, 'quest_id' => 10, 'content' => 'Great for first-time travelers!',      'created_at' => Carbon::parse('2025-03-17'), 'updated_at' => Carbon::parse('2025-03-11')],
            ['user_id' => 8,  'quest_id' => 2,  'content' => 'This quest was so much fun!',          'created_at' => Carbon::parse('2025-03-27'), 'updated_at' => Carbon::parse('2025-03-23')],
            ['user_id' => 3,  'quest_id' => 12, 'content' => 'Really enjoyed exploring this route.', 'created_at' => Carbon::parse('2025-03-12'), 'updated_at' => Carbon::parse('2025-03-15')],
            ['user_id' => 11, 'quest_id' => 3,  'content' => 'Nice scenery and good pacing.',        'created_at' => Carbon::parse('2025-03-19'), 'updated_at' => Carbon::parse('2025-03-24')],
            ['user_id' => 6,  'quest_id' => 1,  'content' => 'Great for first-time travelers!',      'created_at' => Carbon::parse('2025-03-25'), 'updated_at' => Carbon::parse('2025-03-28')],
            ['user_id' => 5,  'quest_id' => 7,  'content' => 'Would recommend to anyone visiting.',  'created_at' => Carbon::parse('2025-03-22'), 'updated_at' => Carbon::parse('2025-03-13')],
            ['user_id' => 9,  'quest_id' => 6,  'content' => 'A bit tiring, but totally worth it.',  'created_at' => Carbon::parse('2025-03-13'), 'updated_at' => Carbon::parse('2025-03-20')],
            ['user_id' => 4,  'quest_id' => 9,  'content' => 'Really enjoyed exploring this route.', 'created_at' => Carbon::parse('2025-03-11'), 'updated_at' => Carbon::parse('2025-03-10')],
        ]);

        DB::table('quest_comment_likes')->insert([
            ['user_id' => 6,  'quest_comment_id' => 12],
            ['user_id' => 3,  'quest_comment_id' => 7],
            ['user_id' => 4,  'quest_comment_id' => 6],
            ['user_id' => 5,  'quest_comment_id' => 1],
            ['user_id' => 3,  'quest_comment_id' => 16],
            ['user_id' => 1,  'quest_comment_id' => 14],
            ['user_id' => 12, 'quest_comment_id' => 11],
            ['user_id' => 10, 'quest_comment_id' => 13],
            ['user_id' => 2,  'quest_comment_id' => 2],
            ['user_id' => 8,  'quest_comment_id' => 30],
            ['user_id' => 11, 'quest_comment_id' => 3],
            ['user_id' => 7,  'quest_comment_id' => 20],
            ['user_id' => 9,  'quest_comment_id' => 18],
            ['user_id' => 6,  'quest_comment_id' => 5],
            ['user_id' => 2,  'quest_comment_id' => 10],
            ['user_id' => 1,  'quest_comment_id' => 21],
            ['user_id' => 12, 'quest_comment_id' => 4],
            ['user_id' => 8,  'quest_comment_id' => 9],
            ['user_id' => 10, 'quest_comment_id' => 24],
            ['user_id' => 5,  'quest_comment_id' => 23],
            ['user_id' => 9,  'quest_comment_id' => 28],
            ['user_id' => 4,  'quest_comment_id' => 19],
            ['user_id' => 11, 'quest_comment_id' => 15],
            ['user_id' => 3,  'quest_comment_id' => 27],
            ['user_id' => 6,  'quest_comment_id' => 8],
            ['user_id' => 2,  'quest_comment_id' => 22],
            ['user_id' => 10, 'quest_comment_id' => 29],
            ['user_id' => 7,  'quest_comment_id' => 17],
            ['user_id' => 8,  'quest_comment_id' => 25],
            ['user_id' => 1,  'quest_comment_id' => 26],
        ]);

        DB::table('page_views')->insert([
            ['page_type' => 'App\Models\Spot',     'page_id' => 3,  'views' => 132, 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(3)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 7,  'views' => 78,  'created_at' => now()->subDays(12), 'updated_at' => now()->subDays(10)],
            ['page_type' => 'App\Models\Business', 'page_id' => 1,  'views' => 246, 'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 9,  'views' => 65,  'created_at' => now()->subDays(18), 'updated_at' => now()->subDays(17)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 11, 'views' => 389, 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['page_type' => 'App\Models\Business', 'page_id' => 5,  'views' => 91,  'created_at' => now()->subDays(7),  'updated_at' => now()->subDays(6)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 2,  'views' => 153, 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(4)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 1,  'views' => 59,  'created_at' => now()->subDays(10), 'updated_at' => now()->subDays(8)],
            ['page_type' => 'App\Models\Business', 'page_id' => 9,  'views' => 277, 'created_at' => now()->subDays(15), 'updated_at' => now()->subDays(14)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 4,  'views' => 112, 'created_at' => now()->subDays(20), 'updated_at' => now()->subDays(19)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 7,  'views' => 88,  'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(6)],
            ['page_type' => 'App\Models\Business', 'page_id' => 6,  'views' => 334, 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(2)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 10, 'views' => 201, 'created_at' => now()->subDays(14), 'updated_at' => now()->subDays(13)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 1,  'views' => 49,  'created_at' => now()->subDays(11), 'updated_at' => now()->subDays(10)],
            ['page_type' => 'App\Models\Business', 'page_id' => 12, 'views' => 312, 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 6,  'views' => 173, 'created_at' => now()->subDays(9),  'updated_at' => now()->subDays(7)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 5,  'views' => 66,  'created_at' => now()->subDays(12), 'updated_at' => now()->subDays(11)],
            ['page_type' => 'App\Models\Business', 'page_id' => 2,  'views' => 198, 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(4)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 10, 'views' => 45,  'created_at' => now()->subDays(17), 'updated_at' => now()->subDays(16)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 4,  'views' => 162, 'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(5)],
            ['page_type' => 'App\Models\Business', 'page_id' => 4,  'views' => 221, 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(3)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 11, 'views' => 107, 'created_at' => now()->subDays(8),  'updated_at' => now()->subDays(8)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 12, 'views' => 95,  'created_at' => now()->subDays(11), 'updated_at' => now()->subDays(10)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 3,  'views' => 120, 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(4)],
            ['page_type' => 'App\Models\Business', 'page_id' => 8,  'views' => 269, 'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(6)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 8,  'views' => 87,  'created_at' => now()->subDays(9),  'updated_at' => now()->subDays(8)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 6,  'views' => 74,  'created_at' => now()->subDays(13), 'updated_at' => now()->subDays(12)],
            ['page_type' => 'App\Models\Business', 'page_id' => 10, 'views' => 311, 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(1)],
            ['page_type' => 'App\Models\Spot',     'page_id' => 2,  'views' => 140, 'created_at' => now()->subDays(10), 'updated_at' => now()->subDays(9)],
            ['page_type' => 'App\Models\Quest',    'page_id' => 8,  'views' => 103, 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(3)],
        ]);

        DB::table('page_view_logs')->insert([
            ['page_id' => 3,  'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.1',  'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(5)],
            ['page_id' => 7,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.2',  'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(3)],
            ['page_id' => 1,  'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.3',  'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['page_id' => 9,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.4',  'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(4)],
            ['page_id' => 11, 'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.5',  'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(6)],
            ['page_id' => 5,  'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.6',  'created_at' => now()->subDays(7),  'updated_at' => now()->subDays(7)],
            ['page_id' => 2,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.7',  'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['page_id' => 1,  'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.8',  'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['page_id' => 9,  'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.9',  'created_at' => now()->subDays(10), 'updated_at' => now()->subDays(10)],
            ['page_id' => 4,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.10', 'created_at' => now()->subDays(8),  'updated_at' => now()->subDays(8)],
            ['page_id' => 7,  'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.11', 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(4)],
            ['page_id' => 6,  'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.12', 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(3)],
            ['page_id' => 10, 'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.13', 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(5)],
            ['page_id' => 1,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.14', 'created_at' => now()->subDays(7),  'updated_at' => now()->subDays(7)],
            ['page_id' => 12, 'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.15', 'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['page_id' => 6,  'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.16', 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['page_id' => 5,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.17', 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(3)],
            ['page_id' => 2,  'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.18', 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(5)],
            ['page_id' => 10, 'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.19', 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['page_id' => 4,  'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.20', 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(4)],
            ['page_id' => 4,  'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.21', 'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(6)],
            ['page_id' => 11, 'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.22', 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(3)],
            ['page_id' => 12, 'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.23', 'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['page_id' => 3,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.24', 'created_at' => now()->subDays(7),  'updated_at' => now()->subDays(7)],
            ['page_id' => 8,  'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.25', 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(5)],
            ['page_id' => 8,  'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.26', 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['page_id' => 6,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.27', 'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['page_id' => 10, 'page_type' => 'App\Models\Business', 'ip_address' => '192.168.1.28', 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(3)],
            ['page_id' => 2,  'page_type' => 'App\Models\Spot',     'ip_address' => '192.168.1.29', 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(4)],
            ['page_id' => 8,  'page_type' => 'App\Models\Quest',    'ip_address' => '192.168.1.30', 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
        ]);

        DB::table('business_photos')->insert([
            ['business_id' => 1,  'image' => 'images/photo-1.jpg',  'priority' => 1, 'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['business_id' => 2,  'image' => 'images/photo-2.jpg',  'priority' => 2, 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(2)],
            ['business_id' => 3,  'image' => 'images/photo-3.jpg',  'priority' => 1, 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(4)],
            ['business_id' => 4,  'image' => 'images/photo-4.jpg',  'priority' => 2, 'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(5)],
            ['business_id' => 5,  'image' => 'images/photo-5.jpg',  'priority' => 3, 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(1)],
            ['business_id' => 6,  'image' => 'images/photo-6.jpg',  'priority' => 1, 'created_at' => now()->subDays(7),  'updated_at' => now()->subDays(3)],
            ['business_id' => 7,  'image' => 'images/photo-7.jpg',  'priority' => 2, 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(2)],
            ['business_id' => 8,  'image' => 'images/photo-8.jpg',  'priority' => 1, 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(2)],
            ['business_id' => 9,  'image' => 'images/photo-9.jpg',  'priority' => 1, 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['business_id' => 10, 'image' => 'images/photo-10.jpg', 'priority' => 2, 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(5)],
            ['business_id' => 11, 'image' => 'images/photo-11.jpg', 'priority' => 1, 'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(4)],
            ['business_id' => 12, 'image' => 'images/photo-12.jpg', 'priority' => 3, 'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['business_id' => 1,  'image' => 'images/photo-13.jpg', 'priority' => 2, 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(3)],
            ['business_id' => 2,  'image' => 'images/photo-14.jpg', 'priority' => 3, 'created_at' => now()->subDays(4),  'updated_at' => now()->subDays(2)],
            ['business_id' => 3,  'image' => 'images/photo-15.jpg', 'priority' => 1, 'created_at' => now()->subDays(7),  'updated_at' => now()->subDays(6)],
            ['business_id' => 4,  'image' => 'images/photo-16.jpg', 'priority' => 2, 'created_at' => now()->subDays(3),  'updated_at' => now()->subDays(1)],
            ['business_id' => 5,  'image' => 'images/photo-17.jpg', 'priority' => 1, 'created_at' => now()->subDays(2),  'updated_at' => now()->subDays(2)],
            ['business_id' => 6,  'image' => 'images/photo-18.jpg', 'priority' => 2, 'created_at' => now()->subDays(1),  'updated_at' => now()->subDays(1)],
            ['business_id' => 7,  'image' => 'images/photo-19.jpg', 'priority' => 3, 'created_at' => now()->subDays(5),  'updated_at' => now()->subDays(5)],
            ['business_id' => 8,  'image' => 'images/photo-20.jpg', 'priority' => 1, 'created_at' => now()->subDays(6),  'updated_at' => now()->subDays(6)],
        ]);

        DB::table('business_likes')->insert([
            ['user_id' => 1,  'business_id' => 5],
            ['user_id' => 2,  'business_id' => 3],
            ['user_id' => 3,  'business_id' => 8],
            ['user_id' => 4,  'business_id' => 1],
            ['user_id' => 5,  'business_id' => 6],
            ['user_id' => 6,  'business_id' => 2],
            ['user_id' => 7,  'business_id' => 9],
            ['user_id' => 8,  'business_id' => 4],
            ['user_id' => 9,  'business_id' => 10],
            ['user_id' => 10, 'business_id' => 7],
            ['user_id' => 11, 'business_id' => 12],
            ['user_id' => 12, 'business_id' => 11],
            ['user_id' => 1,  'business_id' => 6],
            ['user_id' => 2,  'business_id' => 7],
            ['user_id' => 3,  'business_id' => 1],
            ['user_id' => 4,  'business_id' => 10],
            ['user_id' => 5,  'business_id' => 8],
            ['user_id' => 6,  'business_id' => 3],
            ['user_id' => 7,  'business_id' => 12],
            ['user_id' => 8,  'business_id' => 9],
            ['user_id' => 9,  'business_id' => 2],
            ['user_id' => 10, 'business_id' => 5],
            ['user_id' => 11, 'business_id' => 4],
            ['user_id' => 12, 'business_id' => 6],
            ['user_id' => 1,  'business_id' => 11],
            ['user_id' => 2,  'business_id' => 12],
            ['user_id' => 3,  'business_id' => 4],
            ['user_id' => 4,  'business_id' => 8],
            ['user_id' => 5,  'business_id' => 2],
            ['user_id' => 6,  'business_id' => 7],
        ]);

        DB::table('business_info_category')->insert([
            ['id' => 1, 'name' => 'accessibility'],
            ['id' => 2, 'name' => 'facilities'],
            ['id' => 3, 'name' => 'payment option'],
            ['id' => 4, 'name' => 'smoking policy'],
            ['id' => 5, 'name' => 'other'],
        ]);
        
        DB::table('business_info')->insert([
            // accessibility (category_id = 1)
            ['id' => 1, 'business_info_category_id' => 1, 'name' => 'wheelchair'],
            ['id' => 2, 'business_info_category_id' => 1, 'name' => 'elevator access'],
            ['id' => 3, 'business_info_category_id' => 1, 'name' => 'accessible parking'],
            ['id' => 4, 'business_info_category_id' => 1, 'name' => 'braille signage'],
            ['id' => 5, 'business_info_category_id' => 1, 'name' => 'hearing loop system'],
            // facilities (category_id = 2)
            ['id' => 6, 'business_info_category_id' => 2, 'name' => 'free wifi'],
            ['id' => 7, 'business_info_category_id' => 2, 'name' => 'public restroom'],
            ['id' => 8, 'business_info_category_id' => 2, 'name' => 'parking available'],
            ['id' => 9, 'business_info_category_id' => 2, 'name' => 'bicycle parking'],
            ['id' => 10, 'business_info_category_id' => 2, 'name' => 'changing room'],
            ['id' => 11, 'business_info_category_id' => 2, 'name' => 'shower facilities'],
            // payment option (category_id = 3)
            ['id' => 12, 'business_info_category_id' => 3, 'name' => 'credit card accepted'],
            ['id' => 13, 'business_info_category_id' => 3, 'name' => 'digital payment'],
            ['id' => 14, 'business_info_category_id' => 3, 'name' => 'cash only'],
            ['id' => 15, 'business_info_category_id' => 3, 'name' => 'cash payment accepted'],
            ['id' => 16, 'business_info_category_id' => 3, 'name' => 'internation payment card'],
            ['id' => 17, 'business_info_category_id' => 3, 'name' => 'contactless payment'],
            // smoking policy (category_id = 4)
            ['id' => 18, 'business_info_category_id' => 4, 'name' => 'completely non-smoking'],
            ['id' => 19, 'business_info_category_id' => 4, 'name' => 'smoking area available'],
            ['id' => 20, 'business_info_category_id' => 4, 'name' => 'designated smoking section'],
            ['id' => 21, 'business_info_category_id' => 4, 'name' => 'outdoor smoking section'],
            ['id' => 22, 'business_info_category_id' => 4, 'name' => 'smoking permited throughout'],
        ]);

        DB::table('business_details')->insert([
            ['id' => 1, 'business_id' => 1, 'business_info_id' => 1, 'is_valid' => '1'],
            ['id' => 2, 'business_id' => 1, 'business_info_id' => 2, 'is_valid' => '1'],
            ['id' => 3, 'business_id' => 1, 'business_info_id' => 3, 'is_valid' => '1'],
            ['id' => 4, 'business_id' => 1, 'business_info_id' => 4, 'is_valid' => '1'],
            ['id' => 5, 'business_id' => 1, 'business_info_id' => 5, 'is_valid' => '1'],
            ['id' => 6, 'business_id' => 1, 'business_info_id' => 6, 'is_valid' => '1'],
            ['id' => 7, 'business_id' => 1, 'business_info_id' => 7, 'is_valid' => '1'],
            ['id' => 8, 'business_id' => 2, 'business_info_id' => 8, 'is_valid' => '1'],
            ['id' => 9, 'business_id' => 2, 'business_info_id' => 9, 'is_valid' => '1'],
            ['id' => 10, 'business_id' => 2, 'business_info_id' => 10, 'is_valid' => '1'],
            ['id' => 11, 'business_id' => 2, 'business_info_id' => 11, 'is_valid' => '1'],
            ['id' => 12, 'business_id' => 2, 'business_info_id' => 12, 'is_valid' => '1'],
            ['id' => 13, 'business_id' => 2, 'business_info_id' => 13, 'is_valid' => '1'],
            ['id' => 14, 'business_id' => 2, 'business_info_id' => 14, 'is_valid' => '1'],
            ['id' => 15, 'business_id' => 2, 'business_info_id' => 15, 'is_valid' => '1'],
        ]);

        DB::table('faqs')->insert([
            ['question' => 'What is HopQuest?', 
            'answer' => 'HopQuest is a social platform where users can share recommended travel spots and quests (experiences) using photos and descriptions. You can save spots, like others posts, and leave comments.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'Do I need to create an account to use HopQuest?',
            'answer' => 'You can browse posts without an account, but you will need to register to save spots or make posts and comments.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'How is the credibility of posted content ensured?',
            'answer' => 'Posts reflect personal opinions. To maintain reliability, a reporting system is in place, and our team reviews and removes any inappropriate or misleading content.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'Can I view the posted spots on Google Maps?',
            'answer' => 'Yes, each post includes location information, and you can view the spot directly on Google Maps.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'Can travel agencies or tourism facilities post their own locations?',
            'answer' => 'Yes, by registering as a business account, companies can post their own tourist spots and events.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'Are there any restrictions on what I can post?',
            'answer' => 'Posts that violate public order or contain copyrighted content without permission are prohibited. Please refer to our Terms of Service for more details.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'How can I delete my posts or comments?',
            'answer' => 'You can edit or delete your own posts and comments from your My Page. If you need help, feel free to contact our support team.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'How can I prevent others from seeing my posts?',
            'answer' => 'You can set the visibility of each post when publishing. Posts can be made private or limited to followers only. These settings can be changed from your My Page.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'What exactly is a "quest"?',
            'answer' => 'In HopQuest, a "quest" is a themed activity or mission during a trip. Examples include “Visit 3 matcha cafes in Kyoto” or “Climb a mountain to see the sunrise.” You can create and share your own travel quests.',
            'created_at' => now(),
            'updated_at' => now()],
            ['question' => 'What happens when I follow another user?',
            'answer' => 'Posts from users you follow will appear in your "Following" tab, so you can easily keep track of your favorite travel styles and discover new ideas.',
            'created_at' => now(),
            'updated_at' => now()],
        ]);
    }
}